---
- name: "install prometheus"
  shell: |
    sudo useradd --no-create-home prometheus
    sudo mkdir /etc/prometheus
    sudo mkdir /var/lib/prometheus
    wget https://github.com/prometheus/prometheus/releases/download/v2.36.2/prometheus-2.36.2.linux-amd64.tar.gz
    tar xvfz prometheus-2.36.2.linux-amd64.tar.gz
    sudo cp prometheus-2.36.2.linux-amd64/prometheus /usr/local/bin
    sudo cp prometheus-2.36.2.linux-amd64/promtool /usr/local/bin/
    sudo cp -r prometheus-2.36.2.linux-amd64/consoles /etc/prometheus
    sudo cp -r prometheus-2.36.2.linux-amd64/console_libraries /etc/prometheus
    sudo cp prometheus-2.36.2.linux-amd64/promtool /usr/local/bin/
    rm -rf prometheus-2.36.2.linux-amd64.tar.gz prometheus-2.36.2.linux-amd64
- name: "add prometheus.yml"
  become: true
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/
- name: "add prometheus configuration service"
  become: true
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/
- name: "add rules.yml"
  become: true
  copy:
    src: rules.yml
    dest: /etc/prometheus/
 
##-----------------------------------------------------------------------------------------------------
- name: "install alert manager"
  shell: |
    wget https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz
    tar xvfz alertmanager-0.21.0.linux-amd64.tar.gz
    sudo cp alertmanager-0.21.0.linux-amd64/alertmanager /usr/local/bin
    sudo cp alertmanager-0.21.0.linux-amd64/amtool /usr/local/bin/
    sudo mkdir /var/lib/alertmanager
    rm -rf alertmanager*
- name: "add alertmanager.yml"
  become: true
  copy:
    src: alertmanager.yml
    dest: /etc/prometheus/
- name: "add alertmanager.service"
  become: true
  copy:
    src: alertmanager.service
    dest: /etc/systemd/system/
#----------------------------------------------------------------------------------------------------
- name: "enable prometheus service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: prometheus
    enabled: yes
- name: "enable alertmanager service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: alertmanager
    enabled: yes
#- name: "install alert manager"
#  shell: |
#    sudo systemctl daemon-reload
#    sudo systemctl enable alertmanager
#    sudo systemctl start alertmanager
- name: "restart prometheus"
  shell: |
    sudo systemctl restart prometheus
